### ISSUE TITLE
String index out of range: 44

### ISSUE THREAD

**Issue by alitrack** [epam/parso#11]
When parse this sas file, I got the following error messages,
[test.zip](https://github.com/epam/parso/files/525036/test.zip)
btw, it has Chinese character in variable name.

```
--- exec-maven-plugin:1.2.1:exec (default-cli) @ sas ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Exception calling user-defined function: "sasRead(conn1: url=jdbc:columnlist:connection user=SA, /Users/steven/sas/data/test.sas7bdat, null): String index out of range: 44"; SQL statement:
create table sas as SELECT * FROM SASREAD('/Users/steven/sas/data/test.sas7bdat', null)  [90105-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convertInvocation(DbException.java:312)
	at org.h2.engine.FunctionAlias$JavaMethod.getValue(FunctionAlias.java:493)
	at org.h2.expression.JavaFunction.getValueForColumnList(JavaFunction.java:126)
	at org.h2.table.FunctionTable.<init>(FunctionTable.java:66)
	at org.h2.command.Parser.readTableFilter(Parser.java:1237)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1884)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2032)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1878)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1699)
	at org.h2.command.Parser.parseSelect(Parser.java:1687)
	at org.h2.command.Parser.parseCreateTable(Parser.java:6007)
	at org.h2.command.Parser.parseCreate(Parser.java:4217)
	at org.h2.command.Parser.parsePrepared(Parser.java:360)
	at org.h2.command.Parser.parse(Parser.java:315)
	at org.h2.command.Parser.parse(Parser.java:287)
	at org.h2.command.Parser.prepareCommand(Parser.java:252)
	at org.h2.engine.Session.prepareLocal(Session.java:560)
	at org.h2.engine.Session.prepareCommand(Session.java:501)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at com.alitrack.h2.Function.main(Function.java:40)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 44
	at java.lang.String.substring(String.java:1950)
	at com.epam.parso.impl.SasFileParser$ColumnNameSubheader.processSubheader(SasFileParser.java:1209)
	at com.epam.parso.impl.SasFileParser.processPageMetadata(SasFileParser.java:361)
	at com.epam.parso.impl.SasFileParser.processSasFilePageMeta(SasFileParser.java:331)
	at com.epam.parso.impl.SasFileParser.getMetadataFromSasFile(SasFileParser.java:231)
	at com.epam.parso.impl.SasFileParser.<init>(SasFileParser.java:208)
	at com.epam.parso.impl.SasFileParser.<init>(SasFileParser.java:44)
	at com.epam.parso.impl.SasFileParser$Builder.build(SasFileParser.java:996)
	at com.epam.parso.impl.SasFileReaderImpl.<init>(SasFileReaderImpl.java:63)
	at com.alitrack.h2.Function.sasRead(Function.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.h2.engine.FunctionAlias$JavaMethod.getValue(FunctionAlias.java:481)
	... 20 more
```

**Comment by FriedEgg** [comment]
parso does not currently support DBCS encoded files.  While I just recently added support for reading the sas7bdat encoding value metadata, I did not implement using the inferred encoding to parse the file data.

I believe the current setback is with the function ColumnNameSubheader#processSubheader which is performing substrings from the Subheader based on the columnNameLength, which is length in bytes, not the end index for the string.

Additionally, the function SasFileParser#bytesToString should probably use the String constructor with the SasFileParser#encoding value for character set.

This file is encoded with character set=EUC_CN

I did a quick test with the above assumptions and the test file attached reads correctly, however, additional testing would be required.

**Comment by PetrTsurinov** [comment]
@FriedEgg Thank you for your help. You are right in your assumption about the ColumnNameSubheader#processSubheader function. We changed the SasFileParser#bytesToString function and added a constrictor which uses character encoding and after running the test the correct characters were given. But the last of them is encoded with bytes [FB90], and the code table for character set=GB2312 (which is the encoding of this file) has no symbol for this key.
Haven't you faced this problem?

When you say that file attached was read correctly, are you reading the whole file or just the metadata?
The point is that when reading metadata we get the following values: 
pageCount = 1, 
pageType = 512 ('mix' page),
rowCount = 1, 
mixPageRowCount = 7932, 
columnsCount = 1, 
columnType = "java.lang.Number", although the test1.sas7bdat file also contains characters. 
So, Parso reads only one data row and tries to get a number from it. In this case native getDouble method cannot get a number and returns NAN.
Based on this we can assume that this file is damaged. In favor of this shall mention that file cannot be open by Sas Universal Viewer, Sas Viewer, Stattransfer and Dsread.

**Comment by FriedEgg** [comment]
@PetrTsurinov, I did notice these inconsistencies as well, which is why I denoted needing some additional time to test/review.  I can say though, that the data set in reading correctly, as far as I can tell.  The table appears to contain one row with the Chinese character string as the variable name and a '.' as the value, which is SAS equivalent of NaN.  I have not tried opening the data in any of the products you've mentioned, but have opened it in SAS 9.4 directly (which requires special configuration for supporting dbcs, encoding and local to avoid any CEDA/transcoding).

As for the last character in the column name, I do see the same issue with the code page through the JAVA EUC_CN, which does not happen in SAS, so there may be some discrepancy there as well.  I believe this may be due to SAS referring to EUC_CN (GB2312) but actually using a extended version including GBK and/or GB18030.

**Comment by PetrTsurinov** [comment]
Thank you for your answer, but we have some doubts about the dataset correctness. 
When we open test1.sas7bdat we can see text data (some words are hightlighted on the attached picture).
In addition in this file there are such fields as: DATASTEPcustomer id, customer id, firstpurchasetime, DDMMYY and lastpurchasetimeDDMMYY
So we assume that it contains more columns and rows, but may be damaged.
![sas7bdat_content](https://cloud.githubusercontent.com/assets/5285834/19439305/587a1af6-9486-11e6-958c-4d2c4c950e56.png)

**Comment by FriedEgg** [comment]
We will need a comment from @alitrack to aide in rectifying this, then.  Please provide the method used to create this sas7bdat file "test1.sas7bdat" and please confirm the contents of the sas7bdat file.

**Comment by alitrack** [comment]
the code is very simple, both has Chinese variable, but first one will fail, and 2nd is ok.
```
libname lib "Z:\data";
options validvarname=any;

data lib.chinese_column_fails;
柯妮丝麗=234;
run;

data lib.chinese_column_works;
测试=123;
run;
```

btw, [readstat](https://github.com/WizardMac/ReadStat) has the same issue.

**Comment by alitrack** [comment]
(sas7bdat.py](https://bitbucket.org/jaredhobbs/sas7bdat)works 

<img width="771" alt="screen shot 2016-10-18 at 12 05 52 am" src="https://cloud.githubusercontent.com/assets/20972179/19445429/d070d1cc-94c6-11e6-98fd-e60a0f165e84.png">

```python
from sas7bdat import SAS7BDAT
f= SAS7BDAT('c:/soft/fails.sas7bdat',encoding='GBK') 
df = f.to_data_frame()
df
f.convert_file('c:/soft/fails.csv')
```

**Comment by FriedEgg** [comment]
With this information, the test1.sas7bdat file attached here is definitely damaged, in some way.  There is still outstanding issues with the parser, as noted here, but this test file should be ignored.  I have attached two non-corrupt sas7bdat files generated using the same code provided by @alitrack.  The SAS session (and file) encoding was EUC_CN, but Java should probably be GBK, as I noted earlier, instead of the Java version of EUC_CN, which is missing extensions apparently included in SAS.

[CHINESE_ENCODING_TESTS.ZIP](https://github.com/epam/parso/files/534003/CHINESE_ENCODING_TESTS.ZIP)
