### ISSUE TITLE
Failed to parse sas7bdat file

### ISSUE THREAD

**Issue by ruiwanguk** [epam/parso#14]
Hi Team,

We are experiencing some problems with parsing a SAS 9.4 generated sas7bdat file, here is the error message: 

`Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.epam.parso.impl.SasFileParser$ColumnNameSubheader.processSubheader(SasFileParser.java:1219)
	at com.epam.parso.impl.SasFileParser.processPageMetadata(SasFileParser.java:367)
	at com.epam.parso.impl.SasFileParser.processSasFilePageMeta(SasFileParser.java:337)
	at com.epam.parso.impl.SasFileParser.getMetadataFromSasFile(SasFileParser.java:234)
	at com.epam.parso.impl.SasFileParser.<init>(SasFileParser.java:211)
	at com.epam.parso.impl.SasFileParser.<init>(SasFileParser.java:47)
	at com.epam.parso.impl.SasFileParser$Builder.build(SasFileParser.java:1012)
	at com.epam.parso.impl.SasFileReaderImpl.<init>(SasFileReaderImpl.java:51)
	at com.astrazeneca.parso.ParsoTest.main(ParsoTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)`

Any suggestions?

**Comment by PetrTsurinov** [comment]
It appeared that in new SAS files (captured in 9.4 version) some column subheaders (name, format, label) can be at the end of the file. So for such files it's needed to all data from the file to be sure that columns contain correct names, labels and formats.
