### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by nelson2005** [epam/parso#29]
I'm reading a SAS dataset into Apache Spark using the [sas7bdat](https://github.com/saurfang/spark-sas7bdat) library from @saurfang, which uses parso.  The exception happens in the parso code so I'm posting the main issue here, I'll link to it over on saurfang's project as well.

I poked through the code a bit, the proximate cause might be using long instead of integer.

The dataset has the following characteristics:
 ~10 billion rows 
325 variables
Obs length = 2850
compression = CHAR
file size ~ 10TB

The stack trace is
Caused by: java.lang.ArrayIndexOutOfBoundsException
        at java.util.Arrays.copyOfRange(Arrays.java:3521)
        at com.epam.parso.impl.SasFileParser.getBytesFromFile(SasFileParser.java:717)
        at com.epam.parso.impl.SasFileParser.readSubheaderSignature(SasFileParser.java:403)
        at com.epam.parso.impl.SasFileParser.processPageMetadata(SasFileParser.java:372)
        at com.epam.parso.impl.SasFileParser.processNextPage(SasFileParser.java:566)
        at com.epam.parso.impl.SasFileParser.readNextPage(SasFileParser.java:544)
        ... 45 more

**Comment by Tagar** [comment]
it might be same issue as https://github.com/saurfang/spark-sas7bdat/issues/32

**Comment by nelson2005** [comment]
I **think** it's different... I looked into it a bit, I think this one was because the compressed sas7bdat was not splittable, causing the file load to be done by a single executor, which in turn caused trouble for files over 2GB.  Note that this stack trace is different, and also doesn't list the array index

**Comment by printsev** [comment]
Hey @nelson2005 -- is this issue still relevant? There was a long conversation in spark-sas7bdat issues, and as far as I understand, everything is fixed at the moment. Since spark-sas7bdat is just a wrapper, is there an issue with parso itself?

**Comment by nelson2005** [comment]
@printsev I think it was on the spark-sas7bdat.  I don't know of any outstanding issues, I should have closed this before.
