### ISSUE TITLE
java.io.IOException: No available bytes in the input stream

### ISSUE THREAD

**Issue by westonsankey** [epam/parso#53]
I'm running into the following exception when attempting to process a file:

```
java.io.IOException: There are no available bytes in the input stream.
  at com.epam.parso.impl.SasFileParser.getBytesFromFile(SasFileParser.java:768)
  at com.epam.parso.impl.SasFileParser.readSubheaderSignature(SasFileParser.java:423)
  at com.epam.parso.impl.SasFileParser.processPageMetadata(SasFileParser.java:392)
  at com.epam.parso.impl.SasFileParser.processNextPage(SasFileParser.java:591)
  at com.epam.parso.impl.SasFileParser.readNextPage(SasFileParser.java:561)
  at com.epam.parso.impl.SasFileParser.readNext(SasFileParser.java:519)
  at com.epam.parso.impl.SasFileReaderImpl.readNext(SasFileReaderImpl.java:168)
  ... 57 elided
```

The error occurs after processing approximately 400,000 rows, and the file has several million. My code is below:

```scala
import java.io.FileInputStream
import com.epam.parso.impl.SasFileReaderImpl

val sasFileReader = new SasFileReaderImpl(new FileInputStream("test.sas7bdat"))
int numRows = sasFileReader.getSasFileProperties().getRowCount()
int currentRowNum = 0

while (currentRowNum < numRows) {
    val currentRow = sasFileReader.readNext()
    currentRow.foreach(c => print(c + "|"))
    currentRowNum += 1
}
```

**Comment by Yana-Guseva** [comment]
Hi @westonsankey, thank you for reporting this. Is there any way to provide us the source file? Thanks.

**Comment by westonsankey** [comment]
@Yana-Guseva - I ran the code above in a Scala shell on the EMR instance. I'm working on a local test for it now and will provide you with that file and the results once I have it finished.

**Comment by westonsankey** [comment]
@Yana-Guseva - Sorry - misunderstood your question. I am unable to provide the SAS source file. 

For more insight into this issue, it appears to be isolated when running in Scala. I created an equivalent Java program and it was able to parse the data successfully.

**Comment by westonsankey** [comment]
@Yana-Guseva - I am unable to provide the SAS source file.

I created an equivalent program in Java and got the same exception.

**Comment by Yana-Guseva** [comment]
Please tell me which version of Parso are you using? Do you know whether this file was created using the SAS platform and  that there are definitely no errors in it?

It seems that this file contains an offset value that goes beyond the page boundaries for one of subheaders.

**Comment by westonsankey** [comment]
I've tested using versions 2.0.9, 2.0.10, and 2.0.11. I was able to successfully parse the file using the Python sas7bdat library. Not entirely sure what you mean by the offset value going beyond the page boundaries for one of the subheaders, as I don't have much experience with the SAS format.

**Comment by saurabhvermaabd98** [comment]
in my case it is happening with SASYZCR2 compression type

**Comment by PCaff** [comment]
@saurabhvermaabd98 can you please provide a test file with this issue?

**Comment by printsev** [comment]
@westonsankey @saurabhvermaabd98 -- could you please try with parso 2.0.12 as your file might have contained deleted rows, and it was improved in 2.0.12. Also if you have the test file, that would be very helpful if you could share it with us. In the meanwhile I will put the "nodataset" label as it's pretty hard to impossible for us to fix the issue without dataset.
